(define (* a b)
  (define (halve x)
    (/ x 2))
  (define (dub x)
    (+ x x))
  (define (iter x y accumulator)
    (cond ((= y 0) 0)
          ((= y 1) x)
          (else iter x (- y 1) (+ accumulator (dub x)))))
  (iter a b 0))

(* 2 0)
(* 2 1)
(* 2 2)
(* 2 3)
